### ISSUE TITLE
What are you missing?

### ISSUE THREAD

**Issue by Macacoazul01** [Macacoazul01/month_picker_dialog_2#3]
Created this issue to let you request new functionalities.

The comments with more votes or PRs will be prioritized

**Comment by hmkrivoj** [comment]
Hello @Macacoazul01, thank you very much for continuing development of month_picker_dialog and sorry for the poor code base I left behind! 

month_picker_dialog is something I hacked together as a student that I never expected so many people to use. Unfortunately I am unable to maintain it, because I lack the necessary knowledge in Dart and Flutter.

If it's okay with you, I would like to transfer ownership of month_picker_dialog to you so you can move the repository to your Github profile and merge month_picker_dialog_2.

Alternatively, I will [deprecate](https://dart.dev/tools/pub/publishing#discontinue) month_picker_dialog and link to month_picker_dialog_2.

**Comment by Macacoazul01** [comment]
@hmkrivoj as the original one is bigger than this one, it'll be better if I maintain yours than mine. 
Can you please add my email on pub.dev?
gian.b.bettega@gmail.com

I'll deprecate this one after updating the original.
